# Generated by Django 5.2.12 on 2026-03-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_veiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acessorio',
            options={'verbose_name': 'acessório', 'verbose_name_plural': 'acessórios'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'veículo', 'verbose_name_plural': 'veículos'},
        ),
    ]
